#!/usr/bin/env python3.10
from typing import List

from errors import errors_handler
from stats import Statistics
from utils import check_input_data


@errors_handler
def main() -> None:
    print(
        "Программа выводит статистику выволненных часов работниками.\n"
        "Формат ввода данных – имя, пробел, число.\n"
        "Для получения результата статистики повторно нажмите Enter.\n"
        "Введите данные:"
    )
    data: List[List[str | int]] = []
    while True:
        input_data = input()
        if input_data == "":
            break
        try:
            input_data = check_input_data(input_data)
            data.append(input_data)
        except ValueError:
            print("Неверный формат ввода данных\n"
                  "Попробуйте еще раз:")
            continue
    if not data:
        print('Нет данных.')
        return
    statistics = Statistics(data)
    statistics.forming_statistics()
    print(statistics.format_statistic())


if __name__ == "__main__":
    main()
